# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df40baf8b7cb08e4f1e3ac140837a11f4f1966f35f96274a151d903abd2c6ecff886eb3b24afb6a6810106b666624e6a90b25123b33ad991ec1ce194a78c8eec

test:
  secret_key_base: b9f7c4fbd69512867139ca6d44a991fb1383d9a7064925e61c8272ff23838611db8fee4139a8a5f9d45063093c9788188b7c6a2251ecee1cb5057d2ab3a21266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
